pipeline:
  build:
    image: kaitest/alpine-jdk8:0.0.1
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - chmod 777 gradlew
      - ./gradlew build
      - ls
  gcr:
    image: plugins/gcr
    registry: asia.gcr.io
    repo: devops-186506/spring-boot-test
    dockerfile: ./Dockerfile
    tags: ${DRONE_TAG}
    secrets: [google_credentials]
